services:
  - type: web
    name: sentiment-analysis-api
    env: python
    buildCommand: "pip install -r requirements.txt && python -m nltk.downloader stopwords wordnet"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --timeout 120 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6